export const ACCOUNT = 'account';
export const LOGIN = 'login';
export const FORGOT_PASSWORD = 'forgot-password';
export const LAYOUT = 'admin';
export const HOME = 'dashboard';
export const MY_PROFILE='profile';
export const DIRECTORY='staff-directory';
export const ENTREPRENURSHIP ='entreprenurship';
export const BASIC = 'details';
export const PROFILE_PIC = 'profile-img';
export const QUALIFICATION = 'qualification';
export const SHIFT = 'shift';
export const CHANGE_PASSWORD = 'change-password';
export const APPRAISAL = 'appraisal';
export const DEPARTMENTCHANGE='departmentchange'
export const EXPLORE = 'startup/add_pitch';
export const MY_PITCH = 'startup/my_pitch'
export const HOLIDAY_CALENDER ='holiday-calender';
export const JOB_OPENING ='refer-candidate/job_openings';
export const JOB_LIST= 'refer-candidate/list';
export const JOB_DETAILS ='refer-candidate/job_details'
export const POLICY_DOC='policy-documents';
export const REVIEW='monthly-review';
export const PERFORMANCE='monthly-review/my-performance';
export const INTERVIEW_LIST='interview/interview-list';
export const MY_FRESHER_TRAINING='freshers/my_trainings';
export const MY_TRAINING_DETAILS='freshers/training_details_trainee';
export const UPCOMING_TRAININGS = 'upcoming_trainings';
export const ONGOING_TRAININGS = 'ongoing_trainings';
export const MY_TRAININGS='my_trainings';
export const REQUEST_TRAININGS='requested_trainings';
export const TRAINING_DETAILS='training_details_trainee';
export const ASSETS='user';
export const ASSETS_INVENTROY=`${ASSETS}/assets`;
export const ASSETS_REQUESTS=`${ASSETS}/asset-requests`;
export const ASSETS_DECLARATION=`${ASSETS}/asset-declaration`;
export const ATTENDANCE_CALENDAR=`${ASSETS}/attendance`;
export const MANUAL_PUNCH=`${ASSETS}/manual_punch`;
export const PUNCH_LOG=`${ASSETS}/punch_log`;
export const LEAVE=`${ASSETS}/leave`;
export const LEAVE_DETAILS=`${ASSETS}/leave_details/id`;
export const FLOATING_LEAVE=`${ASSETS}/restricted_leave`;
export const TICKETS=`${ASSETS}/tickets`;
export const DSR='dsr';
export const PROJECT='project_dashboard/projects_details';
export const PROJECT_LISTSHOW='#';
export const PROJECT_GRIDSHOW='';
export const PROJECT_DETAIL='detail';
export const DSR_DETAIL = 'dsr/emp_dsr_detail'
export const EDIT_DSR = 'dsr/edit'
export const FOOD = 'food'
export const LUNCH = `${FOOD}/lunch`
export const DINNER = `${FOOD}/dinner`
export const PURCHASE_COUPON='purchase-lunch-coupon'


